#!/usr/bin/env bash

source /afs/andrew.cmu.edu/usr14/vincenth/public/11411/11411-project/setenv
source /afs/andrew.cmu.edu/usr14/vincenth/public/bootstrapenv/bin/virtualenvwrapper.sh
workon nlpp
screen -S coreNLP -dm ./invoke_corenlp
screen -S NER -dm ./invoke_ner
sleep 20
python ask_files/generateqn.py --corenlp-port 40001 --ner-port 40002 $1 $2
screen -S coreNLP -X quit
screen -S NER -X quit
deactivate