#!/usr/bin/env bash

cd stanford-ner-2014-01-04/
java -mx1000m -cp stanford-ner.jar edu.stanford.nlp.ie.NERServer -loadClassifier classifiers/english.muc.7class.distsim.crf.ser.gz -port 40002 -outputFormat inlineXML